name = "whr-moni-bot"
main = "src/worker.js"
compatibility_date = "2026-04-23"

[vars]
DEFAULT_CURRENCY = "SGD"
BOT_TIMEZONE = "Asia/Singapore"
WEBHOOK_PATH = "/telegram/webhook"
LOG_LEVEL = "INFO"

[[d1_databases]]
binding = "DB"
database_name = "traxpense"
database_id = "3b64c4ea-cd11-4a76-81d9-7b9296c4862b"
